services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: contact-book-dev
    ports:
      - "3000:3000"
    volumes:
      # Mount ALL source files for hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      # Mount CSS and style files
      - ./src/index.css:/app/src/index.css
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      # Exclude node_modules to prevent conflicts
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
